ARG NODE_VERSION=12.18.3-buster-slim

FROM node:${NODE_VERSION}
RUN apt-get update && apt-get install -y libsecret-1-dev
ARG version=latest
WORKDIR /home/ide
ADD $version.package.json ./package.json


RUN yarn --pure-lockfile

RUN NODE_OPTIONS="--max_old_space_size=4096" yarn theia build && \
    # TODO: search relevant plugin
    yarn theia download:plugins

RUN yarn --production && \
    yarn autoclean --init && \
    echo *.ts >> .yarnclean && \
    echo *.ts.map >> .yarnclean && \
    echo *.spec.* >> .yarnclean

RUN yarn autoclean --force && \
    yarn cache clean

FROM node:${NODE_VERSION}

# Install Python 3 from source
ARG VERSION=3.8.3

# Install Python 3 from source
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y make build-essential libssl-dev \
RUN apt-get install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
RUN apt-get install -y libncurses5-dev  libncursesw5-dev xz-utils tk-dev \

RUN apt-get update \
    && apt-get install -y python-dev python-pip libsecret-1-0 \
    && pip install --upgrade pip --user \
    && apt-get install -y python3-dev python3-pip \
    && pip3 install --upgrade pip --user \
    && pip3 install python-language-server flake8 autopep8 \

RUN apt-get install -y yarn \
    && apt-get clean \
    && apt-get auto-remove -y \
    && rm -rf /var/cache/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*


# Add user
RUN addgroup bb && \
    adduser -G bb -s /bin/bash -D bb && \
    chmod g+rw /home && \
# Setup folders
    mkdir -p /home/bb/workspace && \
    mkdir -p /home/bb/.m2 && \
    mkdir -p /home/bb/.theia && \
    mkdir -p /home/bb/.gradle && \    
    chown -R bb:bb /home/bb && \
# Configure a nice terminal
    echo "export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /home/bb/.bashrc && \
# Fake poweroff (stops the container from the inside by sending SIGHUP to PID 1)
    echo "alias poweroff='kill -1 1'" >> /home/bb/.bashrc && \
# Setup Path
    echo "export PATH='$MAVEN_HOME/bin:$GRADLE_HOME/bin:$PATH'" >> /home/bb/.bashrc && \
# Setup an initial workspace
    echo '{"recentRoots":["file:///home/bb/"]}' > /home/bb/.theia/recentworkspace.json && \
# Setup settings (file icons theme)
    echo '{"workbench.iconTheme": "vs-seti"}' > /home/bb/.theia/settings.json

# Create directories
RUN mkdir -p /home/project \
    && mkdir -p /home/ide \
    && mkdir -p /home/plugins

COPY --from=0 /home/ide /home/ide
ENV SHELL=/bin/bash \
    THEIA_DEFAULT_PLUGINS=local-dir:/home/plugins

# Use tini 
ENTRYPOINT ["/sbin/tini", "--"]

ENV HOME /home/bb
WORKDIR /home/bb
EXPOSE 3030
ENV USE_LOCAL_GIT true

CMD [ "node", "/home/ide/src-gen/backend/main.js", "/home/bb", "--hostname=0.0.0.0", "--port=3030" ]